CREATE TABLE IF NOT EXISTS "Projects" (
	"ProjectID"			INTEGER PRIMARY KEY AUTOINCREMENT,
	"ProjectName"		VARCHAR(32) NOT NULL UNIQUE,
	"JiraProjectId"		VARCHAR(8) NOT NULL,
	"GitRepositoryPath"	VARCHAR(32) NOT NULL
);

CREATE TABLE IF NOT EXISTS "Commits" (
	"CommitID"		VARCHAR(40) PRIMARY KEY,
	"ProjectName"	VARCHAR(32) NOT NULL,
	"Summary"		NVARCHAR(256),
	"Message"		NVARCHAR(256),
	"Date"			DATE NOT NULL,
	FOREIGN KEY("ProjectName") REFERENCES "Projects"("ProjectName") ON DELETE RESTRICT ON UPDATE CASCADE 
);

CREATE TABLE IF NOT EXISTS "CommitFiles" (
	"CommitID" 	VARCHAR(40) NOT NULL,
	"Path" 		VARCHAR(64) NOT NULL,
	"FileType"		VARCHAR(4) NOT NULL,
	PRIMARY KEY("CommitID","Path"),
	FOREIGN KEY("CommitID") REFERENCES "Commits"("CommitID") ON DELETE RESTRICT ON UPDATE RESTRICT
);

CREATE TABLE IF NOT EXISTS "CommitChanges" (
	"CommitID" 		VARCHAR(40) NOT NULL,
	"MethodName" 	VARCHAR(16) NOT NULL,
	"NewPath" 		VARCHAR(64),
	"NewContent"	TEXT,
	"OldPath" 		VARCHAR(64),
	"OldContent"	TEXT,
	PRIMARY KEY("CommitID","MethodName"),
	FOREIGN KEY("CommitID") REFERENCES "Commits"("CommitID") ON DELETE RESTRICT ON UPDATE RESTRICT
);

CREATE TABLE IF NOT EXISTS "JiraIssues" (
	"IssueID"		VARCHAR(16) PRIMARY KEY,
	"IssueType"		VARCHAR(16) NOT NULL,
	"ProjectName"	VARCHAR(32) NOT NULL,
	"Summary"		NVARCHAR(128),
	"Description"	NVARCHAR(1024),
	"Status"		VARCHAR(8) NOT NULL,
	FOREIGN KEY("ProjectName") REFERENCES "Projects"("ProjectName") ON DELETE RESTRICT ON UPDATE CASCADE
);

CREATE TABLE IF NOT EXISTS "CommitsIssuesLinkage" (
	"CommitID" 	VARCHAR(40) NOT NULL,
	"IssueID" 	VARCHAR(16) NOT NULL,
	PRIMARY KEY("CommitID","IssueID"),
	FOREIGN KEY("CommitID") REFERENCES "Commits"("CommitID") ON DELETE RESTRICT ON UPDATE RESTRICT,
	FOREIGN KEY("IssueID") REFERENCES "JiraIssues"("IssueID") ON DELETE RESTRICT ON UPDATE RESTRICT
);